# Generated by Django 2.2.1 on 2019-05-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190509_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Log entries'},
        ),
    ]
