# Generated by Django 2.2.1 on 2019-05-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190510_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
