# Generated by Django 2.2.1 on 2019-05-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_logentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='delete_older_than',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
