# Generated by Django 2.2.1 on 2019-05-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190529_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='type',
        ),
        migrations.AddField(
            model_name='logentry',
            name='direction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'N/A'), (1, 'REQ'), (2, 'RSP')], default=0),
        ),
    ]
