# Generated by Django 2.2.1 on 2019-06-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190619_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='entries_critical_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_critical_unread_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_debug_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_debug_unread_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_error_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_error_unread_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_info_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_info_unread_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_notset_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_notset_unread_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_warning_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='entries_warning_unread_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
