# Generated by Django 2.2.4 on 2019-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_logentry_bulk_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
